### ISSUE TITLE
Checkout of the default branch fails on Rawhide

### ISSUE THREAD

**Issue by psss** [teemtee/fmf#149]
The `/tests/plan/lint` failed in psss/tmt/pull/997 with the following error:

    fail git ref 'master' is invalid

After investigation I'm able to reproduce the problem on Rawhide with the following code:

```python
import fmf
fmf.base.Tree.node(dict(url="https://github.com/psss/fmf"))
fmf.base.Tree.node(dict(url="https://github.com/psss/fmf"))
```

It seems that git aborts:

```
Traceback (most recent call last):
  File "/tmp/fmf/fmf/utils.py", line 730, in fetch_repo
    run(['git', 'checkout', '-f', ref], cwd=destination, env=env)
  File "/tmp/fmf/fmf/utils.py", line 769, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'git checkout -f __DEFAULT__' died with <Signals.SIGABRT: 6>.
```

Git version:

    git-2.35.0-0.1.rc1.fc36.x86_64

The problem seems to be related to the `fmf` cache handling.

**Comment by psss** [comment]
Filed a bug here: https://bugzilla.redhat.com/show_bug.cgi?id=2042920

**Comment by psss** [comment]
According to the upstream [discussion](https://lore.kernel.org/git/xmqqee52ghwg.fsf@gitster.g/) it seems we are doing unexpected stuff when copying the remote ref to `refs/heads`. It breaks the following `HEAD` rule:

    HEAD must point at a local branch

This would create an incosistent state if `git commit` is used when `__DEFAULT__` branch is checked out. Although this is not our case we should probably find a better way how to store ref to the default branch.

**Comment by psss** [comment]
Solution proposed by Todd in the [upstream thread](https://lore.kernel.org/git/YessbkNZlxLOTzBE@pobox.com/):

    git clone https://github.com/psss/fmf /tmp/fmf
    cd /tmp/fmf
    git switch -c custom-branch
    : work work work
    defbranch=$(git symbolic-ref --short refs/remotes/origin/HEAD)
    git switch -f ${defbranch#*/}
    git reset --hard @{u}

Which is basically to check the remote head file and parse the last part of the ref. This is what we are already doing in `tmt`. Any better idea?
